%YAML:1.0

#common parameters
imu_topic: "/uav47/rs_t265/imu"
image_topic: "/uav47/rs_t265/fisheye1/image_raw"
output_path: "/home/honzabednar/git/vins-mono/output/"

#camera calibration - taken from kalibr, it is pinhole with equi
model_type: KANNALA_BRANDT
camera_name: camera
image_width: 848
image_height: 800
projection_parameters:
   k2: 0.015376196314016226
   k3: -0.00784022349071264
   k4: 0.021489186560738952
   k5: -0.020066975809051545
   mu: 293.4251407468656
   mv: 292.5117270094008
   u0: 424.6945241654842
   v0: 403.72272194863837


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [-0.9997541340649516, -0.021284281252301453, 0.006216976082604166,
          0.021399233299414476, -0.9995895189764269, 0.019049051595095515,
          0.005808978760158633, 0.019177406603821827, 0.9997992212648076]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.01825910015989575, -0.004215659989976112, 0.0736738228498533]
     
#feature tracker paprameters
max_cnt: 150            # max feature number in feature tracking. The bigger number the longer computational time. Default 150.
min_dist: 30            # min distance between two features. Default 30.
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 1              # if using fisheye, turn on it. A fisheye_mask_name has to be specified and placed into /config folder
fisheye_mask_name: "fisheye_mask_848x800.jpg"              # name of the mask file 

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
# BMI055 - it seems correct, the bigger value of the noise, the smaller scale of the final poses are. The lower the noise, the larger the map is. Too small can jump too large without even correct position estimate
acc_n: 0.1          # accelerometer measurement noise standard deviation.
gyr_n: 0.1         # gyroscope measurement noise standard deviation.     
acc_w: 0.0001         # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#loop closure parameters
loop_closure: 1                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 1            # useful in real-time and large project
pose_graph_save_path: "/home/honzabednar/git/vins-mono/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 1        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
