%YAML:1.0

#common parameters
# imu_topic: "/uav1/vio_imu/imu_raw"
imu_topic: "/uav1/vio_imu/imu_filtered"
image_topic: "/mv_25003659/image_raw"
output_path: "/home/honzabednar/git/vins-mono/output/"

model_type: KANNALA_BRANDT
camera_name: camera
image_width: 752
image_height: 480
projection_parameters:
   k2: -0.007054279635535503
   k3: -0.013010999471709818
   k4: 0.007672805064263297
   k5: -0.0034608152598251778
   mu: 218.62328342963636
   mv: 218.84544019573178
   u0: 374.186243114997
   v0: 203.57046644527676

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.9999460372304865, -0.010299564485700676, -0.0013570550661971632,
          0.010299441097893785, 0.9999469545593301, -9.788050568631622e-05,
          0.0013579912071933714, 8.389831506225192e-05, 0.9999990744100494]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   # data: [ 0.0005912074257153667, 0.004133075192077947, 0.024406107641651704]
   data: [ 0.0, 0.0, 0.007]

#feature traker paprameters
max_cnt: 200            # max feature number in feature tracking
min_dist: 20            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 1              # if using fisheye, turn on it. A fisheye_mask_name has to be specified and placed into /config folder
fisheye_mask_name: "fisheye_mask_752x480.jpg"              # name of the mask file 

#optimization parameters
max_solver_time: 0.05  # max solver itration time (ms), to guarantee real time
max_num_iterations: 100   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.4          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.1         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.1         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.1       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#loop closure parameters
loop_closure: 0                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0            # useful in real-time and large project
pose_graph_save_path: "/home/mrs/git/vins-mono/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.01                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 1        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.3      # size of camera marker in RVIZ
