lateral_estimator: "VIO"

# Altitude state estimator:
# HEIGHT - rangefinder, PLANE - height above plane estimated from realsense, BRICK - height above BRICK
altitude_estimator: "VIO"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "VIO" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  # active: ["GPS", "VIO"]
  active: ["VIO"]

heading_estimators:
  active: ["PIXHAWK", "VIO"]

altitude_estimators:
  active: ["VIO"]
